### PR TITLE
Fixed 5ghz injection for LG Nexus 5. When the data rate is not equal …

### PR DESCRIPTION
**Pull request by j3ll3**
…to 15 a TX error occurs

according to dhdutil. The found value 15 is just a found magic number by trying.

### CODE REVIEW

**Comment by matthiasseemoo** [comment]
It is not our intension to call the wlc_d11hdrs_ext function in the sendframe function. The reason for calling wlc_d11hdrs_ext in the inject_frame function is to modify the d11txhdr before calling the sendframe function. If you do not want to modify the d11txhdr, you can simply remove the call to wlc_d11hdrs_ext in the inject_frame function and let the sendframe function append the d11txhdr by calling wlc_sendctl.

**Comment by j3ll3** [comment]
Is there some more documentation about the wlc_sendctl, wlc_d11hdrs_ext etc. functions to understand the functionality? I will move the wlc_d11hdrs_ext back to injection.c but it is difficult to find an efficient implementation without understanding these functions.

**Comment by matthiasseemoo** [comment]
Only by looking at the disassembled or decompiled code in ida.

Am 27.06.2017 5:30 nachm. schrieb "j3ll3" <notifications@github.com>:

**Comment by j3ll3** [comment]
Hi Matthias, Is there a planning to merge this to the master branch? We have a demonstrator project where it would be helpful to have this code into the Android Nexmon app :)

**Comment by matthiasseemoo** [comment]
No I won't merge this. There are two ways of calling the sendframe function either with an already attached d11txhdr header, then it will automatically call the wlc_send_q function, or without this header it will call the wlc_sendctl function. Calling wlc_sendctl in both cases does not make sense. You should adjust the code calling the sendframe function instead.

**Pull request closed without merging**
