### PR TITLE
Add brcmfmac for Kernel 6.1.y

### PR DESCRIPTION
**Pull request by DrSchottky**
Latest official kernel for Raspberry Pi OS is now Linux 6.1.y
Brcmfmac 5.15.y has been adapted to build on newer kernels

Tested with monitor mode on bcm43430a1/bcm43455c0

### CODE REVIEW

**Comment by alexzaporozhets** [comment]
@DrSchottky does this path works for Zero W? or it's only for Pi4 and Zero 2 W?

**Comment by DrSchottky** [comment]
Should work

**Comment by alexzaporozhets** [comment]
I got the following message in dmesg (Pi Zero 2 W)
```[    9.570792] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available```

```pi@zero2w:~ $ uname -a
Linux zero2w 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux```

**Comment by alexzaporozhets** [comment]
@DrSchottky I got the following error in dmesg (Pi Zero 2 W)

**[    9.570792] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available**

```lshw
*-network:1 DISABLED
       description: Wireless interface
       physical id: 3
       logical name: wlan0
       serial: d8:3a:dd:41:34:eb
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=brcmfmac driverversion=7.45.96 firmware=es7 multicast=yes wireless=IEEE 802.11

# modinfo brcmfmac
filename:       /lib/modules/6.1.21-v7+/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko

# dmesg|grep brcmfmac
[    9.267783] brcmfmac: loading out-of-tree module taints kernel.
[    9.267782] brcmfmac: loading out-of-tree module taints kernel.
[    9.306713] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    9.312539] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436s-sdio for chip BCM43430/1
[    9.313040] usbcore: registered new interface driver brcmfmac
[    9.570459] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436s-sdio for chip BCM43430/1
[    9.570698] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436s-sdio for chip BCM43430/1
[    9.570792] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[    9.571429] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Jul  5 2022 21:29:56 version 7.45.96.141 (g53ba0094) FWID 01-eef9b3bf es7
[   11.602820] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[ 1704.382859] brcmfmac: brcmf_vif_add_validate: Attempt to add a MONITOR interface...
[ 1704.382897] brcmfmac: brcmf_mon_add_vif: brcmf_mon_add_vif called
[ 1704.382906] brcmfmac: brcmf_mon_add_vif: Adding vif "mon0"
```

```pi@zero2w:~ $ uname -a
Linux zero2w 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux```

**Comment by DrSchottky** [comment]
That's expected and it should work anyway

**Comment by alexzaporozhets** [comment]
> That's expected and it should work anyway

@DrSchottky the problem is that in monitor mode, we do not receive data via either kismet or tcpdump.

```
sudo iw dev wlan0 set power_save off
sudo iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor
sudo ifconfig wlan0 down
sudo ifconfig mon0 up

pi@zero2w:~ $ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

mon0      IEEE 802.11  Mode:Monitor  Frequency:2.412 GHz
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

pi@zero2w:~ $ sudo tcpdump -i mon0 -v
tcpdump: listening on mon0, link-type IEEE802_11_RADIO (802.11 plus radiotap header), snapshot length 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel

```

**Comment by DrSchottky** [comment]
My bad, I missed that you're not loading the right fw.
See https://github.com/DrSchottky/nexmon/issues/8

**Comment by alexzaporozhets** [comment]
@DrSchottky thank you very much, the problem has been resolved

**Pull request merged**
