### PR TITLE
Add ether_ip_udp_header struct

### PR DESCRIPTION
**Pull request by nethunteros**
Build errors on pi if not added related to udptunnel.c (feel free to provide feedback or other fix but this worked for me).

### CODE REVIEW

**Comment by DanielAW** [comment]
Is there a reason why you removed all our beautiful if clauses in the Makefile? ;-)

**Comment by matthiasseemoo** [comment]
You may also check in an if clause if the kali subdirectory exists and then
execute the hardcoded kali command.

Am 20.12.2016 8:18 nachm. schrieb "DanielAW" <notifications@github.com>:

**Comment by matthiasseemoo** [comment]
I now added the missing struct, however, we need a version of the Makefile that works on both Raspbian 8 and Kali. That means some kind of condition to figure out the correct name of the /lib/modules subdirectory.

**Comment by nethunteros** [comment]
Sorry didn't mean to confuse anyone with hardcoded uname because I was building in chroot'd envrionment.  Thanks for adding missing struct, I will close this issue.

**Pull request closed without merging**
