### PR TITLE
Add brcmfmac_4.19.y-nexmon to bcm43430a1\7_45_41_46

### PR DESCRIPTION
**Pull request by DrSchottky**

### CODE REVIEW

**Comment by gilzhaiek** [comment]
@DrSchottky why did you close this PR? Can this be used on 4.19?

**Comment by DrSchottky** [comment]
> @DrSchottky why did you close this PR? Can this be used on 4.19?

Yes but you can also use the one from bcm43455c0 folder

**Comment by gilzhaiek** [comment]
You saying i can use this https://github.com/seemoo-lab/nexmon/blob/master/firmwares/bcm43455c0/7_45_206/brcmfmac43455-sdio.bin ?
I thought I must use the brcmfmac43430-sdio.bin, isn't the 43455 a different broadcom chip?

**Comment by DrSchottky** [comment]
> You saying i can use this https://github.com/seemoo-lab/nexmon/blob/master/firmwares/bcm43455c0/7_45_206/brcmfmac43455-sdio.bin ? I thought I must use the brcmfmac43430-sdio.bin, isn't the 43455 a different broadcom chip?

No, that's the firmware. I'm talking about the 4.19 brcmfmac kernel module that you can find in patches folder for bcm43455c0

**Pull request closed without merging**
