### PR TITLE
Add aarch64 support to nexutil

### PR DESCRIPTION
**Pull request by DrSchottky**

### CODE REVIEW

**Review by matthiasseemoo — COMMENTED** [review]
why did you have to change patches/includes/types.h to make nexutil work on aarch64? Normally, this file should only be required for building firmware patches. If we have a dependency in nexutil on it, maybe it could be removed.

**Comment by DrSchottky** [comment]
Yes, nexutil includes types.h (moreover with a comment saying it's needed)
https://github.com/seemoo-lab/nexmon/blob/master/utilities/nexutil/nexutil.c#L51

There's a type redefinition happening there, but that doesn't throw errors on armhf since the new typedefs match the already existing ones.

That was the easiest fix, but probably nexutil can be updated to remove type.h dependency.
Let me know what suits best for you

**Comment by DrSchottky** [comment]
Turned out to be easier than expected. Restored old types.h, redefined uint type inside nexutil.c

**Comment by alphafox02** [comment]
I don't suppose it's possible to get this to compile on aarch64 22.04 that comes with a 5.15 kernel?

**Comment by Hudater** [comment]
> I don't suppose it's possible to get this to compile on aarch64 22.04 that comes with a 5.15 kernel?

Did you get it to compile on the pi4 with 5.15 kernel?

**Comment by alphafox02** [comment]
In this video video, but that was a while ago

DragonOS Pi64 Onboard WiFi Monitor Mode w/ Nexmon + Kismet and Chasing Your Tail (Pi4, R28)
https://youtu.be/K4m_J1FChfI

**Pull request merged**
